name: CD-Dev
on:
  push:
    branches: [dev]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '9.0.x' }
      - name: Publish API
        working-directory: api/SkillLink.API
        run: dotnet publish -c Release -o publish
      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: skilllink-api-dev
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_API_DEV }}
          package: api/SkillLink.API/publish

  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/skilllink-front
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run build
      - name: Deploy Frontend to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "frontend/skilllink-front"
          output_location: "frontend/skilllink-front/dist"

  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply DB schema
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DB" < infra/db/001_init.sql
