name: Build, Test & Deploy SkillLink Sithu

on:
  push:
    branches: [sprint-2-QA]
    paths:
      - "SkillLink.API/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [sprint-2-QA]
    paths:
      - "SkillLink.API/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  # Build & Test job
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./SkillLink.API/SkillLink.API.csproj

      - name: Build
        run: dotnet build ./SkillLink.API/SkillLink.API.csproj --configuration Release --no-restore

  # 2️ Build Docker & Push to GHCR
  docker-build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/lahiruranjana/skilllink:latest
          context: ./SkillLink.API
          file: ./SkillLink.API/Dockerfile

  
