name: Build & Deploy - SkillLink API (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # needed for azure/login OIDC

env:
  WEBAPP_NAME: api-skilllink-prod
  PROJECT_PATH: SkillLink.API/SkillLink.API.csproj
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish (Release)
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish /p:UseAppHost=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./drop

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_28EB40238FB64B05AB5E8A629A22EE9F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_91307848C2014A238647F11F268A8BAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D35875B47CC448DDB090C599B1543B31 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ./drop
          # slot-name: production   # optional; production is default

