name: Trigger auto deployment for skill-link-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ sprint-2-QA ]
    paths:
    - '**'
    - '.github/workflows/skill-link-api-AutoDeployTrigger-61a9e4cc-0db6-40d3-84e2-c80a670b6937.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SKILLLINKAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SKILLLINKAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SKILLLINKAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SKILLLINKAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SKILLLINKAPI_REGISTRY_PASSWORD }}
          containerAppName: skill-link-api
          resourceGroup: skilllink
          imageToBuild: ghcr.io/skill-link-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


